version: '3.1'
services:
  app:
    build: .
    ports:
    - 3000:3000
    networks:
    - back-tier
    links:
    - "redis.example.com:redis"
  redis.example.com:
    image: redis:latest
    networks:
    - back-tier
networks:
  back-tier: